import { Note } from './types';

export const INITIAL_NOTES: Note[] = [
  {
    id: 'note-cl10-chem-01',
    title: 'Chemical Reactions & Equations - Complete Chapter Notes',
    subject: 'Science',
    department: 'science',
    grade: 10,
    schoolName: 'Delhi Public School, R.K. Puram',
    schoolCode: 'DPS1001',
    tags: ['Chemistry', 'CBSE', 'Class 10', 'Board Prep', 'Equations'],
    pages: 18,
    sizeMB: 3.2,
    rating: 4.9,
    reviews: 142,
    author: {
      name: 'Aarav Sharma',
      initials: 'AS',
      badge: 'Board Topper 2024',
      badgeStyle: 'bg-emerald-100 text-emerald-800'
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=600',
    isPdf: true,
    fileName: 'Chemical_Reactions_Complete_Notes.pdf',
    fileType: 'application/pdf',
    ownerId: 'system_curated',
  },
  {
    id: 'note-cl10-math-02',
    title: 'Quadratic Equations & Trigonometry Formulas & Shortcuts',
    subject: 'Mathematics',
    department: 'math',
    grade: 10,
    schoolName: 'St. Xavier High School',
    schoolCode: 'SXH2040',
    tags: ['Maths', 'Trigonometry', 'Formulas', 'Quick Revision'],
    pages: 14,
    sizeMB: 2.4,
    rating: 4.8,
    reviews: 98,
    author: {
      name: 'Priya Patel',
      initials: 'PP',
      badge: 'Math Club Lead',
      badgeStyle: 'bg-blue-100 text-blue-800'
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=600',
    isPdf: true,
    fileName: 'Math_Formula_CheatSheet_Class10.pdf',
    fileType: 'application/pdf',
    ownerId: 'system_curated',
  },
  {
    id: 'note-cl12-phy-03',
    title: 'Electrostatics & Current Electricity - Handwritten Derivations',
    subject: 'Physics',
    department: 'science',
    grade: 12,
    schoolName: 'Kendriya Vidyalaya No. 1',
    schoolCode: 'KVN3012',
    tags: ['Physics', 'Derivations', 'Class 12', 'IIT-JEE Prep'],
    pages: 28,
    sizeMB: 4.8,
    rating: 5.0,
    reviews: 215,
    author: {
      name: 'Rohan Verma',
      initials: 'RV',
      badge: '98% Physics Scorer',
      badgeStyle: 'bg-purple-100 text-purple-800'
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=600',
    isPdf: true,
    fileName: 'Electrostatics_Derivations_Class12.pdf',
    fileType: 'application/pdf',
    ownerId: 'system_curated',
  },
  {
    id: 'note-cl12-chem-04',
    title: 'Organic Chemistry Named Reactions & Reaction Mechanisms',
    subject: 'Chemistry',
    department: 'science',
    grade: 12,
    schoolName: 'Modern School, Barakhamba',
    schoolCode: 'MSB4120',
    tags: ['Organic Chemistry', 'NEET Prep', 'Reactions', 'Summary'],
    pages: 22,
    sizeMB: 3.9,
    rating: 4.9,
    reviews: 176,
    author: {
      name: 'Ananya Deshmukh',
      initials: 'AD',
      badge: 'Verified Educator',
      badgeStyle: 'bg-emerald-100 text-emerald-800'
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?auto=format&fit=crop&q=80&w=600',
    isPdf: true,
    fileName: 'Organic_Chemistry_Named_Reactions.pdf',
    fileType: 'application/pdf',
    ownerId: 'system_curated',
  },
  {
    id: 'note-cl9-bio-05',
    title: 'The Fundamental Unit of Life: Cell & Tissues Revision Sheet',
    subject: 'Biology',
    department: 'science',
    grade: 9,
    schoolName: 'The Mother\'s International School',
    schoolCode: 'MIS9010',
    tags: ['Biology', 'Class 9', 'Cell Structure', 'Diagrams'],
    pages: 16,
    sizeMB: 2.8,
    rating: 4.7,
    reviews: 84,
    author: {
      name: 'Kabir Mehta',
      initials: 'KM',
      badge: 'Science Scholar',
      badgeStyle: 'bg-teal-100 text-teal-800'
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&q=80&w=600',
    isPdf: true,
    fileName: 'Cell_Tissues_Detailed_Diagrams.pdf',
    fileType: 'application/pdf',
    ownerId: 'system_curated',
  },
  {
    id: 'note-cl9-sst-06',
    title: 'French Revolution & Nazism - Quick Timeline & High-Yield Questions',
    subject: 'Social Science',
    department: 'humanities',
    grade: 9,
    schoolName: 'DAV Public School',
    schoolCode: 'DAV9155',
    tags: ['History', 'Social Studies', 'Exam Notes', 'Timelines'],
    pages: 12,
    sizeMB: 1.9,
    rating: 4.8,
    reviews: 62,
    author: {
      name: 'Sanya Gupta',
      initials: 'SG',
      badge: 'History Topper',
      badgeStyle: 'bg-amber-100 text-amber-800'
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&q=80&w=600',
    isPdf: true,
    fileName: 'French_Revolution_HighYield_Notes.pdf',
    fileType: 'application/pdf',
    ownerId: 'system_curated',
  },
  {
    id: 'note-cl8-math-07',
    title: 'Linear Equations in One Variable & Algebraic Identities',
    subject: 'Mathematics',
    department: 'math',
    grade: 8,
    schoolName: 'National Public School',
    schoolCode: 'NPS8008',
    tags: ['Algebra', 'Class 8', 'NCERT Solutions', 'Step by Step'],
    pages: 15,
    sizeMB: 2.1,
    rating: 4.7,
    reviews: 53,
    author: {
      name: 'Vikram Joshi',
      initials: 'VJ',
      badge: 'Peer Tutor',
      badgeStyle: 'bg-blue-100 text-blue-800'
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=600',
    isPdf: true,
    fileName: 'Linear_Equations_Identities_Class8.pdf',
    fileType: 'application/pdf',
    ownerId: 'system_curated',
  },
  {
    id: 'note-cl7-sci-08',
    title: 'Nutrition in Plants & Animals - Illustrated Mind Maps',
    subject: 'Science',
    department: 'science',
    grade: 7,
    schoolName: 'Bhavan\'s Vidya Mandir',
    schoolCode: 'BVM7070',
    tags: ['Class 7', 'Science', 'Mind Maps', 'Diagrams'],
    pages: 10,
    sizeMB: 1.6,
    rating: 4.9,
    reviews: 41,
    author: {
      name: 'Tanvi Nair',
      initials: 'TN',
      badge: 'Creative Notes Award',
      badgeStyle: 'bg-pink-100 text-pink-800'
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?auto=format&fit=crop&q=80&w=600',
    isPdf: true,
    fileName: 'Nutrition_Illustrated_Mindmaps.pdf',
    fileType: 'application/pdf',
    ownerId: 'system_curated',
  },
  {
    id: 'note-cl6-sci-09',
    title: 'Components of Food, Fibre to Fabric & Sorting Materials',
    subject: 'General Science',
    department: 'science',
    grade: 6,
    schoolName: 'Army Public School',
    schoolCode: 'APS6010',
    tags: ['Science', 'Class 6', 'Definitions', 'Activity Summary'],
    pages: 11,
    sizeMB: 1.4,
    rating: 4.6,
    reviews: 35,
    author: {
      name: 'Arjun Singhania',
      initials: 'AS',
      badge: 'Star Student',
      badgeStyle: 'bg-indigo-100 text-indigo-800'
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600',
    isPdf: true,
    fileName: 'Components_of_Food_Summary_Class6.pdf',
    fileType: 'application/pdf',
    ownerId: 'system_curated',
  },
  {
    id: 'note-cl5-evs-10',
    title: 'Super Senses & A Snake Charmer\'s Story - Environmental Studies',
    subject: 'Environmental Studies (EVS)',
    department: 'humanities',
    grade: 5,
    schoolName: 'Lotus Valley International School',
    schoolCode: 'LVIS501',
    tags: ['EVS', 'Class 5', 'Illustrated', 'Animal Senses'],
    pages: 8,
    sizeMB: 1.1,
    rating: 4.9,
    reviews: 47,
    author: {
      name: 'Meera Kulkarni',
      initials: 'MK',
      badge: 'Junior Editor',
      badgeStyle: 'bg-emerald-100 text-emerald-800'
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600',
    isPdf: true,
    fileName: 'Super_Senses_Class5_EVS.pdf',
    fileType: 'application/pdf',
    ownerId: 'system_curated',
  }
];
